### ISSUE TITLE
load module

### ISSUE THREAD

**Issue by ChoiJi-Hye** [BostonGene/MFP#4]
Hi,

How can I use 'portraits' module?
When I enter 'from portraits.plotting import pca_plot', error occurs with '**ModuleNotFoundError : No module named 'portraits'** '.

I tried pip upgrade and pip install portraits, and get opened code 'MFP-master.zip'.
However, I don't know how to do it.

Could you tell me how to use it?

**Comment by joan-yanqiong** [comment]
Hi @ChoiJi-Hye, I think I might have an idea of what the problem can be, see the link below: 
[importing modules](https://www.programiz.com/python-programming/modules )

Here you can see that Python looks at the current working directory or at the environment variable `PYTHONPATH`, so my guess is that the portraits module is not in the same directory as your file.

I hope this helps.

**Comment by ChoiJi-Hye** [comment]
Oh my god!! I've got it. Thank you so much!!
I haven't solved that problem all day yesterday, but thanks to you, I can use tool.

I couldn't have done it without you.
Thank you for your guidance.
